/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vector1;

import javax.swing.JOptionPane;

/**
 *
 * @author liborio
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    double v[];
    double Acum1, M;
    double NMen, NMay;

    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtLongitud = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenarM = new javax.swing.JButton();
        cmdLlenarA = new javax.swing.JButton();
        cmdNMYM = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setText("Numeros De Un Vector");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", 0, 0, new java.awt.Font("Georgia", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 20));

        jLabel8.setText("Longitud");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", 0, 0, new java.awt.Font("Georgia", 0, 12))); // NOI18N

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", 0, 0, new java.awt.Font("Georgia", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        cmdLlenarM.setText("Llenado Manual");
        cmdLlenarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarMActionPerformed(evt);
            }
        });
        cmdLlenarM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdLlenarMKeyTyped(evt);
            }
        });
        jPanel4.add(cmdLlenarM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        cmdLlenarA.setText("Llenado Automatico");
        cmdLlenarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        cmdNMYM.setText("Numero Mayor Y Menor");
        cmdNMYM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNMYMActionPerformed(evt);
            }
        });
        jPanel4.add(cmdNMYM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(406, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed

        int I;
        if (txtLongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Valor En La Longitud", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
        } else if (Integer.parseInt(txtLongitud.getText().trim()) == 0) {
            JOptionPane.showMessageDialog(this, "Digite Un Valor Mayor Que 0", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
            txtLongitud.selectAll();
        } else {
            I = Integer.parseInt(txtLongitud.getText());
            v = new double[I];
            JOptionPane.showMessageDialog(this, "Su Vector Ha Sido Creado Satisfactoriamente");
            txtLongitud.setText("");

            cmdCrear.setEnabled(false);
            cmdLlenarM.setEnabled(true);
            cmdLlenarA.setEnabled(true);
            cmdNMYM.setEnabled(false);
            cmdMostrar.setEnabled(false);
            cmdBorrar.setEnabled(true);
            txtLongitud.setEditable(false);

        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarMActionPerformed

        double J;
        Acum1 = 0;
        M = 1;

        for (int i = 0; i < v.length; i++) {
            J = Double.parseDouble(JOptionPane.showInputDialog("Digite El Valor De La Posicion" + i));
            v[i] = J;
            Acum1 = Acum1 + v[i];
            M = M * v[i];
        }
        JOptionPane.showMessageDialog(this, "Vector Llenado Correctamente");
        for (int i = 0; i < v.length; i++) {
            if (i == 0) {
                NMay = v[0];
                NMen = v[0];
            }
            if (v[i] > NMay) {
                NMay = v[i];
            }
            if (v[i] < NMen) {
                NMen = v[i];
            }
        }

        cmdCrear.setEnabled(false);
        cmdLlenarM.setEnabled(false);
        cmdLlenarA.setEnabled(false);
        cmdNMYM.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtLongitud.setEditable(false);
    }//GEN-LAST:event_cmdLlenarMActionPerformed

    private void cmdLlenarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAActionPerformed

        double J;
        Acum1 = 0;
        M = 1;
        for (int i = 0; i < v.length; i++) {
            J = (int) (Math.random() * 25 + 1);
            v[i] = J;
            Acum1 = Acum1 + v[i];
            M = M * v[i];
        }
        for (int i = 0; i < v.length; i++) {
            if (i == 0) {
                NMay = v[0];
                NMen = v[0];
            }
            if (v[i] > NMay) {
                NMay = v[i];
            }
            if (v[i] < NMen) {
                NMen = v[i];
            }
        }
        JOptionPane.showMessageDialog(this, "Vector Llenado Con Exito");

        cmdCrear.setEnabled(false);
        cmdLlenarM.setEnabled(false);
        cmdLlenarA.setEnabled(false);
        cmdNMYM.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtLongitud.setEditable(false);
    }//GEN-LAST:event_cmdLlenarAActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed

        txtLongitud.setText("");
        txtResultado.setText("");
        txtLongitud.requestFocusInWindow();
        v = null;

        cmdCrear.setEnabled(true);
        cmdLlenarM.setEnabled(false);
        cmdLlenarA.setEnabled(false);
        cmdNMYM.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        txtLongitud.setEditable(true);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        txtResultado.setText("");
        txtResultado.append("La Sumatoria es: " + Acum1 + "\nLa Productoria es: " + M + "\nEl Número Mayor Es: " + NMay + "\nEl Número Menor es: " + NMen);

        cmdCrear.setEnabled(false);
        cmdLlenarM.setEnabled(false);
        cmdLlenarA.setEnabled(false);
        cmdNMYM.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtLongitud.setEditable(false);

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdNMYMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNMYMActionPerformed

        txtResultado.setText("");
        txtResultado.append("El Numero Mayor Es: " + NMay + "\nEl Numero Menor es: " + NMen);
        cmdCrear.setEnabled(false);
        cmdLlenarM.setEnabled(false);
        cmdLlenarA.setEnabled(false);
        cmdNMYM.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        txtLongitud.setEditable(false);

    }//GEN-LAST:event_cmdNMYMActionPerformed

    private void cmdLlenarMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdLlenarMKeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cmdLlenarMKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenarA;
    private javax.swing.JButton cmdLlenarM;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdNMYM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
